# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: notice
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make secrets1.yml
      run: |
        echo "학번: $STUDENT" >> secrets1.yml
      env: 
        STUDENT: ${{ secrets.STUDENT }}
    - name: Make secrets2.yml
      run: |
        echo "비밀번호: $PW" >> secrets2.yml
      env:
        PW: ${{ secrets.PW }}
    - name: Make secrets3.yml
      run: |
        echo "bot-token: $BOTTOKEN" >> secrets3.yml
      env:
        BOTTOKEN: ${{ secrets.BOTTOKEN }}
    - name: Run main.py
      run: |
        python main.py
